# Application definition for doing "in situ" development
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: accord-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: volumes.mongo.size
        value: "5Gi"
      - name: images.accord-service.repository
        value: "quay.io/accord/docker-python-image"
      - name: images.accord-service.tag
        value: "latest"
      - name: images.accord-service.stdin
        value: "true"
    path: accord-dev
    repoURL: https://github.com/parsley42/accord-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
