
# Override this with your own domain
appDomain: "example.com"

# Override this by environment. The main UI will have the URL
# <envUrl>.<appDomain>, e.g. "accord.example.com". User pods will
# have this in the final dashed segment,
# e.g. "theia-python-mst3k-abcde-accord.example.com".
envUrl: "accord"

images:
  accord_web:
    repository: quay.io/accord/accord-web
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "develop"
    stdin: false
  accord_service:
    repository: quay.io/accord/accord-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "develop"
    # For doing in-cluster development
    stdin: false
  mongo:
    repository: mongo
    tag: "latest"
  envoy:
    repository: "docker.io/envoyproxy/envoy"
    tag: "v1.16-latest"

imagePullSecrets: []

# Class for PVCs
volumeClass: "longhorn"

volumes:
  mongo:
    size: 40Gi

# User Pod Configuration
userPods:
  envoy:
    externalPort: "10000"
    adminPort: "9901"
    match: {}
  storage:
    home:
      type: "hostPath"
      prefix: "/home"
      format: "short"
    project:
      type: "hostPath"
      prefix: "/project"
      format: "groupname"

# Note: most of the original ingress definition is currently unused.
ingress:
#  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: chart-example.local
  #     paths: []
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

accordServiceHeaderMap: |
  uwsgi_param eppn $HTTP_EPPN;
  uwsgi_param sn $HTTP_SN;
  uwsgi_param givenName $HTTP_GIVENNAME;
  uwsgi_param displayName $HTTP_DISPLAYNAME;
  uwsgi_param cn $HTTP_CN;
  uwsgi_param affiliation $HTTP_UNSCOPED_AFFILIATION;
  uwsgi_param uid $HTTP_UID;
  uwsgi_param gid $HTTP_GID;
  uwsgi_param email $HTTP_EPPN;
  uwsgi_param title $HTTP_TITLE;
  uwsgi_param entitlement $HTTP_ENTITLEMENT;
  uwsgi_param targetedID $HTTP_TARGETED_ID;
  uwsgi_param persistentID $HTTP_PERSISTENT_ID;
  uwsgi_param isMemberOf $HTTP_ISMEMBEROF;
  uwsgi_param telephoneNumber $HTTP_TELEPHONENUMBER;
  uwsgi_param initials $HTTP_INITIALS;
  uwsgi_param description $HTTP_DESCRIPTION;
  uwsgi_param carLicense $HTTP_CARLICENSE;
  uwsgi_param departmentNumber $HTTP_DEPARTMENTNUMBER;
  uwsgi_param employeeNumber $HTTP_EMPLOYEENUMBER;
  uwsgi_param employeeType $HTTP_EMPLOYEETYPE;
  uwsgi_param preferencialLanguage $HTTP_PREFERREDLANGUAGE;
  uwsgi_param manager $HTTP_MANAGER;
  uwsgi_param seealSO $HTTP_SEEALSO;
  uwsgi_param fax $HTTP_FACSIMILETELEPHONENUMBER;
  uwsgi_param street $HTTP_STREET;
  uwsgi_param pobox $HTTP_POSTOFFICEBOX;
  uwsgi_param pc $HTTP_POSTALCODE;
  uwsgi_param st $HTTP_ST;
  uwsgi_param l $HTTP_L;
  uwsgi_param o $HTTP_O;
  uwsgi_param ou $HTTP_OU;
  uwsgi_param businessCategory $HTTP_BUSINESSCATEGORY;
  uwsgi_param physicalDeliveryOfficeName $HTTP_PHYSICALDELIVERYOFFICENAME;

# NOTE: unused data from original template below

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
