apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: accord
    server: https://kubernetes.default.svc
  project: default
  source:
    # helm:
    #   parameters:
    #   - name: volumes.mongo.size
    #     value: "5Gi"
    path: accord
    repoURL: https://github.com/uvarc/accord-deploy.git
    targetRevision: HEAD
