---
# accord-service podlib and mongo configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: accord-service-configmap
  namespace: {{ .Release.Namespace }}
data:
   BUILD_ENV: "prod"
   PODLIB_NAMESPACE: "{{ .Release.Namespace }}"
   PODLIB_INCLUSTER: "true"
   PODLIB_CONFIG: "userpod"
   CONNECTIONS_JSON: |
      {"ENV": "prod", "MONGODB": {"HOSTS":["mongo"], "PORT":"27017"}, "INCOMMON_SSO": {"HOSTS": [""], "PORT":"", "CLIENT_ID":"", "CLIENT_SECRET":""}}
---
# accord-service connections configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-service-config
  namespace: {{ .Release.Namespace }}
data:
  connections.json: |
    {
      "ENV": "dev",
      "ELASTIC_SEARCH": {
        "HOSTS": ["localhost"],
        "PORT": "9200",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "INCOMMON_SSO": {
        "HOSTS": [""],
        "PORT": "",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "SMTP": {
        "HOSTS": ["localhost"],
        "PORT": "25",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "AMAZON_S3": {
        "HOSTS": ["s3.amazonaws.com"],
        "PORT": "",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      }
    }
  nginx.conf: |
    server {
      listen 0.0.0.0:5000;
      server_name localhost;

      # max upload size
      client_max_body_size 75M;

      # underscores_in_headers on;

      location / {
        include uwsgi_params;
        {{- with .Values.accordServiceHeaderMap }}
        {{- . | nindent 8 }}
        {{- end }}
        uwsgi_pass unix:///accord_service/app.sock;
      }
    }
---
# accord-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-service
  name: accord-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-service
  template:
    metadata:
      labels:
        app: accord-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.images.accord_service.repository }}:{{ .Values.images.accord_service.tag }}"
        name: accord-service
        imagePullPolicy: "{{ .Values.images.accord_service.pullPolicy }}"
        command:
        - /usr/bin/supervisord
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_PASSWORD
        - name: APP_DOMAIN
          value: {{ .Values.appDomain }}
        - name: APP_URL
          value: {{ .Values.envUrl }}
        envFrom:
        - configMapRef:
            name: accord-service-configmap
        volumeMounts:
        - name: accord-service-config-service
          mountPath: /etc/private/accord
        - name: accord-service-config-nginx
          mountPath: /etc/nginx/sites-available
      volumes:
      - name: accord-service-config-service
        configMap:
          name: accord-service-config
          items:
          - key: connections.json
            path: connections.json
      volumes:
      - name: accord-service-config-nginx
        configMap:
          name: accord-service-config
          items:
          - key: nginx.conf
            path: default
---
# accord-service service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accord-service
  name: accord-service-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "accord-service-port"
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: accord-service
---
# accord-service ingress definition
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: accord-service
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: "{{ .Values.envUrl }}.{{ .Values.appDomain }}"
    http:
      paths:
      - path: /accord/api/
        backend:
          serviceName: accord-service-service
          servicePort: 80
