---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-web
  name: accord-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-web
  template:
    metadata:
      labels:
        app: accord-web
    spec:
      containers:
      - image: "{{ .Values.images.accord_web.repository }}:{{ .Values.images.accord_web.tag }}"
        name: accord-web
        imagePullPolicy: "{{ .Values.images.accord_web.pullPolicy }}"
        stdin: "{{ .Values.images.accord_web.stdin }}"
        volumeMounts:
        - name: accord-web-assets-config
          mountPath: /usr/share/nginx/html/assets/config
      volumes:
      - name: accord-web-assets-config
        configMap:
          name: accord-web-assets-config
