apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-service-connections-json
  namespace: {{ .Release.Namespace }}
data:
  connections.json: |
    {
      "ENV": "dev",
      "ELASTIC_SEARCH": {
        "HOSTS": ["localhost"],
        "PORT": "9200",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "INCOMMON_SSO": {
        "HOSTS": [""],
        "PORT": "",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "SMTP": {
        "HOSTS": ["localhost"],
        "PORT": "25",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      },
      "AMAZON_S3": {
        "HOSTS": ["s3.amazonaws.com"],
        "PORT": "",
        "CLIENT_ID": "",
        "CLIENT_SECRET": ""
      }
    }
