apiVersion: v1
kind: Service
metadata:
  labels:
    app: accord-service
  name: accord-service-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "accord-service-port"
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: accord-service
