---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-web
  name: accord-web
  namespace: accord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-web
  template:
    metadata:
      labels:
        app: accord-web
    spec:
      containers:
        - image: "{{ .Values.images.accord-web.repository }}:{{ .Values.images.accord-web.tag }}"
          name: accord-web
          imagePullPolicy: {{ .Values.images.accord-web.pullPolicy }}
          stdin: {{ .Values.images.accord-web.stdin }}
          volumeMounts:
            - name: accord-web-assets-config
              mountPath: /usr/share/nginx/html/assets/config
      volumes:
        - name: accord-web-assets-config
          configMap:
            name: accord-web-assets-config
