apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-web-assets-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
     "production": false,
     "api": "https://{{ .Values.envUrl }}.{{ .Values.appDomain }}/accord/api/"
    }  
