---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-service
  name: accord-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-service
  template:
    metadata:
      labels:
        app: accord-service
    spec:
      containers:
      - image: "{{ .Values.images.accord_service.repository }}:{{ .Values.images.accord_service.tag }}"
        name: accord-service
        imagePullPolicy: "{{ .Values.images.accord_service.pullPolicy }}"
        stdin: {{ .Values.images.accord_service.stdin }}
        envFrom:
        - configMapRef:
            name: accord-service-configmap
        volumeMounts:
        - name: accord-service-connections-json
          mountPath: /etc/private/accord
      volumes:
      - name: accord-service-connections-json
        configMap:
          name: accord-service-connections-json
