apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
spec:
#  serviceName: mongo
#  replicas: 1
#  updateStrategy:
#    type: RollingUpdate
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: "{{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}"
        args:
          - "mongod"
        ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
        - name: mongodb-scripts
          mountPath: /docker-entrypoint-initdb.d
        env:
        # Env for official dockerhub image
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_PASSWORD
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_DB
      volumes:
      - name: mongodb-scripts
        configMap:
          name: mongo-config
          items:
          - key: init-mongo.sh
            path: init-mongo.sh
      - name: mongo-pvc
        persistentVolumeClaim:
          claimName: mongo-pvc
